apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 3Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /nfs/vol1 
    server: master
  persistentVolumeReclaimPolicy: Retain
